name: CI
on: 
  push: 
    branches:
      - dockercoins-1.1
jobs:
  kubernetes: 
    runs-on: ubuntu-18.04    
    steps:
      - name: checkout
        uses: actions/checkout@v2
      - name: build-hasher
        run: docker build -t dockercoins-hasher:testing hasher/
      - name: build-redis
        run: docker build -t dockercoins-redis:testing redis/
      - name: build-rng
        run: docker build -t dockercoins-rng:testing rng/
      - name: build-webui
        run: docker build -t dockercoins-webui:testing webui/
      - name: build-worker
        run: docker build -t dockercoins-worker:testing worker/
      - name: kube-init
        run: |
          uuid=$( md5sum kube-compose.yaml | cut -d\  -f1 )
          git clone --single-branch -b v1.2 https://github.com/academiaonline-org/kubernetes $uuid
          source $uuid/bin/cluster/ubuntu18/install-docker-kubelet.sh
          source $uuid/bin/cluster/ubuntu18/install-leader.sh
          master=$( kubectl get node | grep master | awk '{ print $1 }' )
          kubectl taint node $master node-role.kubernetes.io/master:NoSchedule-
          rm -rf $uuid
          
          
          
          
