name: CI
on: 
  push: 
    branches:
      - dockercoins-1.1
jobs:
  kubernetes: 
    runs-on: ubuntu-18.04    
    steps:
      - name: checkout
        uses: actions/checkout@v2
      - name: build
        run: docker build...
