name: CI
on: 
  push: 
    branches:
      - dockercoins-1.1
jobs:
  kubernetes: 
    runs-on: ubuntu-18.04    
    steps:
      - name: checkout
        uses: actions/checkout@v2
      - name: build
        run: |
          docker build -t dockercoins-hasher:testing hasher/
          docker build -t dockercoins-redis:testing redis/
          docker build -t dockercoins-rng:testing rng/
          docker build -t dockercoins-webui:testing webui/
          docker build -t dockercoins-worker:testing worker/
          
          
